---
version: '2'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "8080"
    volumes:
      - "./node/my:/usr/src/app/my"
      - "./node/test:/usr/src/app/test"
    working_dir: /usr/src/app
    command: "node my/myfirst.js"
